name: CI
on:
  - push
  - pull_request
jobs:

  cabal:
    name: ${{ matrix.os }} - GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc:
          - 9.2.7
          - 9.4.4
          - 9.6.1
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: |
        cabal test all

    - name: Save cache
      uses: actions/cache/save@v3
      if: always()
      with:
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
