name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.os }} - GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc:
          - 9.8
          - 9.6
          - 9.4
          - 9.2
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      id:   setup
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all --dry-run

    - name: Restore cache
      uses: actions/cache/restore@v3
      id:   cache
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key:  ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-plan-${{ hashfiles('dist-newstyle/cache/plan.json') }}
        restore-keys: |
              ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-

    - name: Build dependencies
      run: cabal build all --dependencies-only

    - run: cabal build all
    - run: cabal test all
    - run: cabal haddock
    - run: cabal check
    - run: cabal sdist

    - name: Save cache
      uses: actions/cache/save@v3
      if:   always()
      with:
        key:  ${{ steps.cache.outputs.cache-primary-key }}
        path: ${{ steps.setup.outputs.cabal-store }}
